### ISSUE TITLE
Presentera antal röster per Hund/Katt

### ISSUE THREAD

**Issue by kaos** [SvenskaSpel/example-voting-app#23]
Utöver att det visas hur många procent av rösterna som hund resp katt har fått, visa även antalet röster för de samma.

Du kommer behöva lägga till dessa värden i angular app:ens `$scope` i https://github.com/SvenskaSpel/example-voting-app/blob/e6fd86302e31d12fb50e86e36152cd255c641fb2/result/views/app.js#L23
för att sen kunna använda dem i template uttryck i `index.html`-filen på motsvarande vis som för procenten: https://github.com/SvenskaSpel/example-voting-app/blob/e6fd86302e31d12fb50e86e36152cd255c641fb2/result/views/index.html#L24

**Comment by LouiseSerenhov** [comment]
Vi paxar! /Louise och Freja
